services:
  - type: web
    name: muzzeum
    env: node
    plan: standard
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
